ping: Add missing preprocesses checks around setlocale() calls
This fixes build with -Wimplicit-function-declaration on old distros
(it looks like to be issue on Debian oldstable, CentOS 7,
Ubuntu Xenial and on musl (Alpine), but not on recent ones):

[10/22] cc -Iping/ping.p -Iping -I../ping -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c99 -g -include config.h -include git-version.h -MD -MQ ping/ping.p/ping.c.o -MF ping/ping.p/ping.c.o.d -o ping/ping.p/ping.c.o -c ../ping/ping.c
FAILED: ping/ping.p/ping.c.o
cc -Iping/ping.p -Iping -I../ping -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c99 -g -include config.h -include git-version.h -MD -MQ ping/ping.p/ping.c.o -MF ping/ping.p/ping.c.o.d -o ping/ping.p/ping.c.o -c ../ping/ping.c
../ping/ping.c: In function ‘ping_strtod’:
../ping/ping.c:181:2: warning: implicit declaration of function ‘setlocale’ [-Wimplicit-function-declaration]
181 |  setlocale(LC_ALL, "C");
|  ^~~~~~~~~
../ping/ping.c:181:12: error: ‘LC_ALL’ undeclared (first use in this function); did you mean ‘P_ALL’?
181 |  setlocale(LC_ALL, "C");
|            ^~~~~~
|            P_ALL
../ping/ping.c:181:12: note: each undeclared identifier is reported only once for each function it appears in

Fixes: 918e824 ("ping: add support for sub-second timeouts")
Fixes: #284

Signed-off-by: Noah Meyerhans <noahm@debian.org>
[ pvorel: add missing include to have <locale.h> ]
Signed-off-by: Petr Vorel <pvorel@suse.cz>