error: Unify output of error() implementation with glibc
error() from glibc uses program_invocation_name by default (argv[0],
./builddir/ping/ping). Our implementation (used at least when compiled
against musl) used program_invocation_short_name. Although glibc could
also use program_invocation_short_name (via #define program_name
program_invocation_short_name) it's probably better to use
program_invocation_name, therefore changed our implementation.

Fixes: 129fa3a ("common: move error() portability go-around to common library")
Signed-off-by: Petr Vorel <pvorel@suse.cz>