ci: Move to Leap 15 container image
Default Leap image is 16.0, which is having temporary issues:

    Installing /usr/bin/getaddrinfo
      PEVANS/Socket-GetAddrInfo-0.22.tar.gz
      ./Build install  -- OK
    + zypper --non-interactive install --no-recommends clang docbook_5 docbook5-xsl-stylesheets file gcc gettext-tools git iproute2 jq libcap-devel libcap-progs libidn2-devel libxslt-tools meson ninja pkg-config perl-Test-Command
    Refreshing service 'openSUSE'.
    Loading repository data...
    Reading installed packages...
    Package 'perl-Test-Command' not found.
    'pkg-config' not found in package names. Trying capabilities.
    Error: Process completed with exit code 104.

Temporarily switch to Leap 16 to fix it.

Reported-by: Danielle Ratson <danieller@nvidia.com>
Signed-off-by: Petr Vorel <pvorel@suse.cz>